#Commands used to calculate relative distance of TEs to cCREs

ln -s ../TE_derived_cCREs_human/ENCODTE.25.*.upset.txt .
ln -s ../reference_files/reAnno_hg38.bed .

bedtools intersect -a ENCODTE.25.PLS.upset.txt -b /scratch/adu/encode_te_analysis/cCRE_overlaps/rerun_ccRE_overlaps/reAnno_hg38.bed -loj |perl -lane 'if ($F[-3] eq "."){$F[-3] = "None"}else{@class=split /\//, $F[-3];$F[-3]=$class[0]};print join("\t",@F)' > ENCODTE.25.PLS.TE.txt
bedtools intersect -a ENCODTE.25.pELS.upset.txt -b /scratch/adu/encode_te_analysis/cCRE_overlaps/rerun_ccRE_overlaps/reAnno_hg38.bed -loj |perl -lane 'if ($F[-3] eq "."){$F[-3] = "None"}else{@class=split /\//, $F[-3];$F[-3]=$class[0]};print join("\t",@F)' > ENCODTE.25.pELS.TE.txt
bedtools intersect -a ENCODTE.25.dELS.upset.txt -b /scratch/adu/encode_te_analysis/cCRE_overlaps/rerun_ccRE_overlaps/reAnno_hg38.bed -loj |perl -lane 'if ($F[-3] eq "."){$F[-3] = "None"}else{@class=split /\//, $F[-3];$F[-3]=$class[0]};print join("\t",@F)' > ENCODTE.25.dELS.TE.txt
bedtools intersect -a ENCODTE.25.DNase-H3K4me3.upset.txt -b /scratch/adu/encode_te_analysis/cCRE_overlaps/rerun_ccRE_overlaps/reAnno_hg38.bed -loj |perl -lane 'if ($F[-3] eq "."){$F[-3] = "None"}else{@class=split /\//, $F[-3];$F[-3]=$class[0]};print join("\t",@F)' > ENCODTE.25.DNase-H3K4me3.TE.txt
bedtools intersect -a ENCODTE.25.CTCF.upset.txt -b /scratch/adu/encode_te_analysis/cCRE_overlaps/rerun_ccRE_overlaps/reAnno_hg38.bed -loj |perl -lane 'if ($F[-3] eq "."){$F[-3] = "None"}else{@class=split /\//, $F[-3];$F[-3]=$class[0]};print join("\t",@F)' > ENCODTE.25.CTCF.TE.txt
cat ENCODTE.25.CTCF.TE.txt ENCODTE.25.PLS.TE.txt ENCODTE.25.pELS.TE.txt ENCODTE.25.dELS.TE.txt ENCODTE.25.DNase-H3K4me3.TE.txt |sort -k1,1 -k2,2n -k3,3n > ENCODTE.25.allcCRE.TE.txt
perl -lane 'next if $F[31] eq ".";splice @F,5,26;print join("\t",@F)' ENCODTE.25.allcCRE.TE.txt > ENCODTE.allCRE.TEonly.txt

#Cell/tissue agnostic relative distances
for cre in PLS pELS dELS DNase-H3K4me3 CTCF; do bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt) -a <(perl -lane 'print $_ if $F[4] =~ /^SINE/' reAnno_hg38.bed) > reldist.$cre.SINE.txt;done
for cre in PLS pELS dELS DNase-H3K4me3 CTCF; do bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt) -a <(perl -lane 'print $_ if $F[4] =~ /^LINE/' reAnno_hg38.bed) > reldist.$cre.LINE.txt;done
for cre in PLS pELS dELS DNase-H3K4me3 CTCF; do bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt) -a <(perl -lane 'print $_ if $F[4] =~ /^DNA/' reAnno_hg38.bed) > reldist.$cre.DNA.txt;done
for cre in PLS pELS dELS DNase-H3K4me3 CTCF; do bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt) -a <(perl -lane 'print $_ if $F[4] =~ /^LTR/' reAnno_hg38.bed) > reldist.$cre.LTR.txt;done

echo -e "reldist\tcount\ttotal\tfraction\tcCRE\tTE" > reldist.allCRE.allTE.txt; for cre in PLS pELS dELS DNase-H3K4me3 CTCF;do for te in DNA LTR SINE LINE;do perl -slne 'next if $.==1;$_.="\t$cre\t$te";print $_' -- -cre=$cre -te=$te reldist.$cre.$te.txt >> reldist.allCRE.allTE.txt;done;done

for cre in PLS pELS dELS DNase-H3K4me3; do bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt|bedtools intersect -a stdin -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(perl -lane 'print $_ if $F[9] =~ /SINE/ && $F[0] ne "chrY"' ENCODTE.$cre.TEonly.txt) > reldist.$cre.SINEinCRE.txt;done
for cre in PLS pELS dELS DNase-H3K4me3; do bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt|bedtools intersect -a stdin -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(perl -lane 'print $_ if $F[9] =~ /LINE/ && $F[0] ne "chrY"' ENCODTE.$cre.TEonly.txt) > reldist.$cre.LINEinCRE.txt;done
for cre in PLS pELS dELS DNase-H3K4me3; do bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt|bedtools intersect -a stdin -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(perl -lane 'print $_ if $F[9] =~ /DNA/ && $F[0] ne "chrY"' ENCODTE.$cre.TEonly.txt) > reldist.$cre.DNAinCRE.txt;done
for cre in PLS pELS dELS DNase-H3K4me3; do bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt|bedtools intersect -a stdin -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(perl -lane 'print $_ if $F[9] =~ /LTR/ && $F[0] ne "chrY"' ENCODTE.$cre.TEonly.txt) > reldist.$cre.LTRinCRE.txt;done

bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt|bedtools intersect -a stdin -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(perl -lane 'print $_ if $F[9] =~ /SINE/ && $F[0] ne "chrY"' ENCODTE.CTCF-only.TEonly.txt) > reldist.CTCF-only.SINEinCRE.txt
bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt|bedtools intersect -a stdin -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(perl -lane 'print $_ if $F[9] =~ /LINE/ && $F[0] ne "chrY"' ENCODTE.CTCF-only.TEonly.txt) > reldist.CTCF-only.LINEinCRE.txt
bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt|bedtools intersect -a stdin -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(perl -lane 'print $_ if $F[9] =~ /DNA/ && $F[0] ne "chrY"' ENCODTE.CTCF-only.TEonly.txt) > reldist.CTCF-only.DNAinCRE.txt
bedtools reldist -b <(tail -n +2 ENCODTE.25.$cre.upset.txt|bedtools intersect -a stdin -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(perl -lane 'print $_ if $F[9] =~ /LTR/ && $F[0] ne "chrY"' ENCODTE.CTCF-only.TEonly.txt) > reldist.CTCF-only.LTRinCRE.txt

echo -e "reldist\tcount\ttotal\tfraction\tcCRE\tTE" > reldist.allCRE.allTEinCRE.txt; for cre in PLS pELS dELS DNase-H3K4me3 CTCF-only;do for te in DNA LTR SINE LINE;do perl -slne 'next if $.==1;$_.="\t$cre\t$te";print $_' -- -cre=$cre -te=$te reldist.$cre.${te}inCRE.txt >> reldist.allCRE.allTEinCRE.txt;done;done

cat <(perl -lape '$_.="\tallTE"' reldist.allCRE.allTE.txt) <(tail -n +2 reldist.allCRE.allTEinCRE.txt|perl -lpe '$_.="\tTEinCRE"')|perl -lane '$F[4]=$F[4] eq "CTCF"?"CTCF-only":$F[4];print join("\t",@F)' > reldist.allCRE.combine.txt

#Cell/tissue type specific relative distances
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do perl -slane 'print $_ if $F[-1] eq $cell' -- -cell=$cell ENCODTE.25.PLS.pretty.sort.bed > ENCODTE.${cell}.PLS.pretty.sort.bed; done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do perl -slane 'print $_ if $F[-1] eq $cell' -- -cell=$cell ENCODTE.25.pELS.pretty.sort.bed > ENCODTE.${cell}.pELS.pretty.sort.bed; done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do perl -slane 'print $_ if $F[-1] eq $cell' -- -cell=$cell ENCODTE.25.dELS.pretty.sort.bed > ENCODTE.${cell}.dELS.pretty.sort.bed; done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do perl -slane 'print $_ if $F[-1] eq $cell' -- -cell=$cell ENCODTE.25.CTCF.pretty.sort.bed > ENCODTE.${cell}.CTCF.pretty.sort.bed; done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do perl -slane 'print $_ if $F[-1] eq $cell' -- -cell=$cell ENCODTE.25.DNase-H3K4me3.pretty.sort.bed > ENCODTE.${cell}.DNase-H3K4me3.pretty.sort.bed; done

for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do for cre in PLS pELS dELS DNase-H3K4me3; do bedtools reldist -b <(bedtools intersect -a ENCODTE.$cell.$cre.pretty.sort.bed -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(bedtools intersect -a ../ENCODTE.$cre.TEonly.txt -b ENCODTE.$cell.$cre.pretty.sort.bed -wa|perl -lane 'print $_ if $F[9] =~ /SINE/ && $F[0] ne "chrY"') > reldist.$cell.$cre.SINEinCRE.txt;done;done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do for cre in PLS pELS dELS DNase-H3K4me3; do bedtools reldist -b <(bedtools intersect -a ENCODTE.$cell.$cre.pretty.sort.bed -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(bedtools intersect -a ../ENCODTE.$cre.TEonly.txt -b ENCODTE.$cell.$cre.pretty.sort.bed -wa|perl -lane 'print $_ if $F[9] =~ /LINE/ && $F[0] ne "chrY"') > reldist.$cell.$cre.LINEinCRE.txt;done;done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do for cre in PLS pELS dELS DNase-H3K4me3; do bedtools reldist -b <(bedtools intersect -a ENCODTE.$cell.$cre.pretty.sort.bed -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(bedtools intersect -a ../ENCODTE.$cre.TEonly.txt -b ENCODTE.$cell.$cre.pretty.sort.bed -wa|perl -lane 'print $_ if $F[9] =~ /LTR/ && $F[0] ne "chrY"') > reldist.$cell.$cre.LTRinCRE.txt;done;done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do for cre in PLS pELS dELS DNase-H3K4me3; do bedtools reldist -b <(bedtools intersect -a ENCODTE.$cell.$cre.pretty.sort.bed -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(bedtools intersect -a ../ENCODTE.$cre.TEonly.txt -b ENCODTE.$cell.$cre.pretty.sort.bed -wa|perl -lane 'print $_ if $F[9] =~ /DNA/ && $F[0] ne "chrY"') > reldist.$cell.$cre.DNAinCRE.txt;done;done

for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do bedtools reldist -b <(bedtools intersect -a ENCODTE.$cell.CTCF.pretty.sort.bed -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(bedtools intersect -a ENCODTE.CTCF-only.TEonly.txt -b ENCODTE.$cell.CTCF.pretty.sort.bed -wa|perl -lane 'print $_ if $F[9] =~ /SINE/ && $F[0] ne "chrY"') > reldist.$cell.CTCF-only.SINEinCRE.txt;done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do bedtools reldist -b <(bedtools intersect -a ENCODTE.$cell.CTCF.pretty.sort.bed -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(bedtools intersect -a ENCODTE.CTCF-only.TEonly.txt -b ENCODTE.$cell.CTCF.pretty.sort.bed -wa|perl -lane 'print $_ if $F[9] =~ /SINE/ && $F[0] ne "chrY"') > reldist.$cell.CTCF-only.LINEinCRE.txt;done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do bedtools reldist -b <(bedtools intersect -a ENCODTE.$cell.CTCF.pretty.sort.bed -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(bedtools intersect -a ENCODTE.CTCF-only.TEonly.txt -b ENCODTE.$cell.CTCF.pretty.sort.bed -wa|perl -lane 'print $_ if $F[9] =~ /LTR/ && $F[0] ne "chrY"') > reldist.$cell.CTCF-only.LTRinCRE.txt;done
for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do bedtools reldist -b <(bedtools intersect -a ENCODTE.$cell.CTCF.pretty.sort.bed -b ENCODTE.allCRE.TEonly.txt -v|perl -lane 'print $_ if $F[0] ne "chrY"') -a <(bedtools intersect -a ENCODTE.CTCF-only.TEonly.txt -b ENCODTE.$cell.CTCF.pretty.sort.bed -wa|perl -lane 'print $_ if $F[9] =~ /DNA/ && $F[0] ne "chrY"') > reldist.$cell.CTCF-only.DNAinCRE.txt;done

echo -e "reldist\tcount\ttotal\tfraction\tcell\tcCRE\tTE" > reldist.eachcell.allCRE.allTEinCRE.txt; for cell in "A673" "AG04450" "B_cell" "CD14-positive" "GM12878" "GM23338" "H1_embryonic" "HCT116" "HeLa-S3" "HepG2" "IMR-90" "K562" "MCF-7" "MM.1S" "OCI-LY7" "PC-3" "PC-9" "Panc1" "astrocyte" "bipolar" "fibroblast" "hepatocyte" "keratinocyte" "myotube" "neural"; do for cre in PLS pELS dELS DNase-H3K4me3 CTCF-only;do for te in DNA LTR SINE LINE;do perl -slne 'next if $.==1;$_.="\t$cell\t$cre\t$te";print $_' -- -cell=$cell -cre=$cre -te=$te reldist.$cell.$cre.${te}inCRE.txt >> reldist.eachcell.allCRE.allTEinCRE.txt;done;done;done
perl -MList::Util=sum -lane '{unless ($.==1){push @{$h{$F[-1]}{$F[-2]}{$F[0]}{'frac'}}, $F[3];push @{$h{$F[-1]}{$F[-2]}{$F[0]}{'total'}}, $F[2];push @{$h{$F[-1]}{$F[-2]}{$F[0]}{'count'}}, $F[1]}}END{foreach $te(keys %h){foreach $ccre(keys %{$h{$te}}){foreach $dist(keys %{${h}{$te}{$ccre}}){$frac_sum = sum(@{${h}{$te}{$ccre}{$dist}{'frac'}});$count_sum = sum(@{${h}{$te}{$ccre}{$dist}{'count'}});$total_sum = sum(@{${h}{$te}{$ccre}{$dist}{'total'}});$frac=$frac_sum/@{${h}{$te}{$ccre}{$dist}{'frac'}};$count= int($count_sum/@{${h}{$te}{$ccre}{$dist}{'count'}}+0.5);$total= int($total_sum/@{${h}{$te}{$ccre}{$dist}{'count'}}+0.5);print join("\t",$dist,$count,$total,$frac,$ccre,$te,"mean")}}}}' reldist.eachcell.allCRE.allTEinCRE.txt|sort -k5,5 -k6,6 -k1,1n > reldist.mean.allCRE.allTEinCRE.txt

cat reldist.allCRE.combine.txt reldist.mean.allCRE.allTEinCRE.txt > reldist.allCRE.combine.final.txt

